[package]
name = "rapier-bevy"
version = "0.1.0"
edition = "2024"

[lib]
name = "rapier_bevy"
path = "src/lib.rs"

[[bin]]
name = "rapier-bevy"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.16.1", features = ["configurable_error_handler"] }
bevy_rapier3d = { version = "0.31.0", features = ["simd-stable", "debug-render-3d"] }
bincode = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tobj = "4.0.3"
crossbeam-channel = "0.5"
bevy_mod_rounded_box = "0.10"
